
platform :ios, '8.0'
target 'KKLSwift' do
	use_frameworks!
	
	pod 'RxSwift'
	pod 'SnapKit'
	
	target 'KKLSwiftTests' do
		inherit! :search_paths
		# Pods for testing
	end
	
	target 'KKLSwiftUITests' do
		inherit! :search_paths
		# Pods for testing
	end
	
end
