
platform :ios, '8.0'
target 'KKLSwift' do
	use_frameworks!
	
	pod 'RxSwift',    '~> 4.0'
	pod 'RxCocoa',    '~> 4.0'
	pod 'Masonry'
	pod 'SnapKit', '~> 4.0.0'
	
	
	target 'KKLSwiftTests' do
		inherit! :search_paths
		# Pods for testing
	end
	
	target 'KKLSwiftUITests' do
		inherit! :search_paths
		# Pods for testing
	end
	
end
